//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QR_Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIST_LISTAEVENTO
    {
        public decimal ID_LISTA { get; set; }
        public decimal ID_EVENTO { get; set; }
        public decimal ID_ENTIDAD { get; set; }
        public string ASISTE { get; set; }
        public Nullable<byte> NUMERO_ACOMP { get; set; }
    }
}
