//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QR_Testing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTOS()
        {
            this.ASIST_LISTAEVENTO = new HashSet<ASIST_LISTAEVENTO>();
        }
    
        public int ID_EVENTO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public string LUGAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASIST_LISTAEVENTO> ASIST_LISTAEVENTO { get; set; }
    }
}
